### PR TITLE
Collect resource usage

### PR DESCRIPTION
**Pull request by elbuo8**

### CODE REVIEW

**Comment by jfromaniello** [comment]
whats the performance impact of this change and the previous one? 

Can you measure running `node perf/take_unlimited.js`?

**Comment by elbuo8** [comment]
@jfromaniello on it.

**Comment by elbuo8** [comment]
```
┌─────────────┬─────────┐
│ Requests    │ 200000  │
├─────────────┼─────────┤
│ Concurrency │ 1000    │
├─────────────┼─────────┤
│ Total time  │ 7216 ms │
├─────────────┼─────────┤
│ RPS         │ 27716   │
├─────────────┼─────────┤
│ Errored     │ 0       │
├─────────────┼─────────┤
│ Mean        │ 26.78   │
├─────────────┼─────────┤
│ P50         │ 26      │
├─────────────┼─────────┤
│ P60         │ 30      │
├─────────────┼─────────┤
│ P70         │ 33      │
├─────────────┼─────────┤
│ P80         │ 37      │
├─────────────┼─────────┤
│ P90         │ 42      │
├─────────────┼─────────┤
│ P95         │ 47      │
├─────────────┼─────────┤
│ P97         │ 54      │
├─────────────┼─────────┤
│ Max         │ 136     │
├─────────────┼─────────┤
│ Min         │ 4       │
└─────────────┴─────────┘
```

With no-op. No DD or statsd host was passed in the `perf/config.yml` so I'm assuming this is how it was tested.

**Comment by elbuo8** [comment]
```
┌─────────────┬──────────┐
│ Requests    │ 200000   │
├─────────────┼──────────┤
│ Concurrency │ 1000     │
├─────────────┼──────────┤
│ Total time  │ 13046 ms │
├─────────────┼──────────┤
│ RPS         │ 15330    │
├─────────────┼──────────┤
│ Errored     │ 0        │
├─────────────┼──────────┤
│ Mean        │ 55.60    │
├─────────────┼──────────┤
│ P50         │ 52       │
├─────────────┼──────────┤
│ P60         │ 56       │
├─────────────┼──────────┤
│ P70         │ 59       │
├─────────────┼──────────┤
│ P80         │ 64       │
├─────────────┼──────────┤
│ P90         │ 73       │
├─────────────┼──────────┤
│ P95         │ 86       │
├─────────────┼──────────┤
│ P97         │ 99       │
├─────────────┼──────────┤
│ Max         │ 272      │
├─────────────┼──────────┤
│ Min         │ 11       │
└─────────────┴──────────┘
```

Adding a local statsd agent *without* collecting resource usage. This is what would be in prod at the moment unless we dropped DD.

**Comment by elbuo8** [comment]
```
┌─────────────┬──────────┐
│ Requests    │ 200000   │
├─────────────┼──────────┤
│ Concurrency │ 1000     │
├─────────────┼──────────┤
│ Total time  │ 13624 ms │
├─────────────┼──────────┤
│ RPS         │ 14679    │
├─────────────┼──────────┤
│ Errored     │ 0        │
├─────────────┼──────────┤
│ Mean        │ 56.55    │
├─────────────┼──────────┤
│ P50         │ 54       │
├─────────────┼──────────┤
│ P60         │ 57       │
├─────────────┼──────────┤
│ P70         │ 60       │
├─────────────┼──────────┤
│ P80         │ 65       │
├─────────────┼──────────┤
│ P90         │ 72       │
├─────────────┼──────────┤
│ P95         │ 82       │
├─────────────┼──────────┤
│ P97         │ 98       │
├─────────────┼──────────┤
│ Max         │ 211      │
├─────────────┼──────────┤
│ Min         │ 11       │
└─────────────┴──────────┘
```

Collecting resources.

**Comment by elbuo8** [comment]
```
┌─────────────┬──────────┐
│ Requests    │ 200000   │
├─────────────┼──────────┤
│ Concurrency │ 1000     │
├─────────────┼──────────┤
│ Total time  │ 10079 ms │
├─────────────┼──────────┤
│ RPS         │ 19843    │
├─────────────┼──────────┤
│ Errored     │ 0        │
├─────────────┼──────────┤
│ Mean        │ 43.30    │
├─────────────┼──────────┤
│ P50         │ 41       │
├─────────────┼──────────┤
│ P60         │ 45       │
├─────────────┼──────────┤
│ P70         │ 49       │
├─────────────┼──────────┤
│ P80         │ 54       │
├─────────────┼──────────┤
│ P90         │ 62       │
├─────────────┼──────────┤
│ P95         │ 69       │
├─────────────┼──────────┤
│ P97         │ 74       │
├─────────────┼──────────┤
│ Max         │ 162      │
├─────────────┼──────────┤
│ Min         │ 9        │
└─────────────┴──────────┘
```

With sample rate of `0.1` with resource collection.

**Comment by elbuo8** [comment]
```
┌─────────────┬─────────┐
│ Requests    │ 200000  │
├─────────────┼─────────┤
│ Concurrency │ 1000    │
├─────────────┼─────────┤
│ Total time  │ 9958 ms │
├─────────────┼─────────┤
│ RPS         │ 20084   │
├─────────────┼─────────┤
│ Errored     │ 0       │
├─────────────┼─────────┤
│ Mean        │ 42.78   │
├─────────────┼─────────┤
│ P50         │ 41      │
├─────────────┼─────────┤
│ P60         │ 45      │
├─────────────┼─────────┤
│ P70         │ 50      │
├─────────────┼─────────┤
│ P80         │ 55      │
├─────────────┼─────────┤
│ P90         │ 63      │
├─────────────┼─────────┤
│ P95         │ 71      │
├─────────────┼─────────┤
│ P97         │ 78      │
├─────────────┼─────────┤
│ Max         │ 188     │
├─────────────┼─────────┤
│ Min         │ 7       │
└─────────────┴─────────┘
```

Sample rate of `0.1` *without* resource collection.

**Comment by elbuo8** [comment]
Assuming we want DD running in production (which we should 🤔 ) the difference of enabling resource collection and not doing so is roughly `4.20%`.

**Pull request merged**
